### ISSUE TITLE
Application architecture 

### ISSUE THREAD

**Issue by revgum** [osulp/tresbien#1]
- [ ] Break down the current TRES workflow
- [ ] Decompose the TRES expense report form into models
- [ ] Identify models and functionality that requires basic CRUD
